// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent that summarizes sentiment from raw text.
 *
 * - generateSentimentSummary - A function that handles the sentiment summarization process.
 * - SentimentSummaryInput - The input type for the generateSentimentSummary function.
 * - SentimentSummaryOutput - The return type for the generateSentimentSummary function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const SentimentSummaryInputSchema = z.object({
  redditContent: z.string().describe('Raw text content from Reddit posts and comments.'),
  youtubeContent: z.string().describe('Raw text content from YouTube video transcripts and comments.'),
  xContent: z.string().describe('Raw text content from X (formerly Twitter) posts and comments.'),
});
export type SentimentSummaryInput = z.infer<typeof SentimentSummaryInputSchema>;

const SentimentSummaryOutputSchema = z.object({
  summary: z.string().describe('A concise, neutral summary of the overall sentiment from the provided content.'),
  positivePoints: z.array(z.string()).describe('A list of key positive points or recurring positive feedback.'),
  negativePoints: z.array(z.string()).describe('A list of key negative points or recurring negative feedback.'),
});
export type SentimentSummaryOutput = z.infer<typeof SentimentSummaryOutputSchema>;

export async function generateSentimentSummary(
  input: SentimentSummaryInput
): Promise<SentimentSummaryOutput> {
  return sentimentSummaryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'sentimentSummaryPrompt',
  input: { schema: SentimentSummaryInputSchema },
  output: { schema: SentimentSummaryOutputSchema },
  prompt: `You are a sentiment analysis expert for financial trading firms. Your task is to analyze raw text from social media and generate a neutral, factual summary.

Analyze the following content. Based on the text from Reddit, YouTube, and X, provide:
1.  A concise summary of the overall community sentiment.
2.  A list of the most common positive points.
3.  A list of the most common negative points.

Do not add any commentary or opinions. Base your output solely on the provided text.

Reddit Content:
---
{{{redditContent}}}
---

YouTube Content:
---
{{{youtubeContent}}}
---

X Content:
---
{{{xContent}}}
---
`,
});

const sentimentSummaryFlow = ai.defineFlow(
  {
    name: 'sentimentSummaryFlow',
    inputSchema: SentimentSummaryInputSchema,
    outputSchema: SentimentSummaryOutputSchema,
  },
  async input => {
    const { output } = await prompt(input);
    return output!;
  }
);
