
import type { GlobalOffer, PropFirm, Article, TradingResource } from './types';

export const mockGlobalOffers: GlobalOffer[] = [
  { id: '1', text: 'VISIBLE OFFER TEXT TEST', affiliateLink: '#', isActive: true },
  { id: '2', text: 'FundYourDreams: Pass guarantee or free retry!', affiliateLink: '#', isActive: true },
  { id: '3', text: 'NewFirmX: 10% bonus on payout with code FINDER10', affiliateLink: '#', isActive: true },
];

export const mockPropFirms: PropFirm[] = [
  {
    id: '1',
    slug: 'apex-trader-funding',
    name: 'Apex Trader Funding',
    logoUrl: 'https://placehold.co/100x50.png?text=ApexTF',
    websiteUrl: 'https://apextraderfunding.com/', // Example, replace with actual if known
    affiliateLink: '#', // Replace with actual affiliate link
    briefDescription: 'Popular choice for futures traders, offering straightforward evaluation and scaling.',
    fullReview: 'Apex Trader Funding is well-regarded in the futures trading community for its simple evaluation process and generous profit splits. They primarily focus on futures contracts and offer a variety of account sizes to suit different trader needs. Their Rithmic-based connection is standard for futures platforms.',
    pros: ["Simple 1-step evaluation", "No daily drawdown limit on many accounts", "Trade on actual market data during evaluation", "Quick funding after passing"],
    cons: ["Primarily futures-focused", "Monthly fee for evaluation accounts until passed", "Trailing drawdown can be tricky for some"],
    keyFeatures: ['Pass in as few as 7 days', 'Up to 20 accounts allowed', 'Trade on NinjaTrader, Tradovate, Rithmic'],
    keyInfoSnippets: [
      { label: 'Profit Split', value: '90% (first $25k per account), then 80%' },
      { label: 'Max Drawdown', value: 'Trailing Threshold' },
      { label: 'Platforms', value: 'NinjaTrader, Rithmic, Tradovate' },
    ],
    offerBadgeLabel: 'Pass in 7 Days!',
    fundingModels: ['1-Step Evaluation'],
    profitSplit: '90% (first $25k), then 80%',
    drawdownRules: 'Trailing Threshold Drawdown (varies by account size)',
    profitTarget: '6% - 7% (varies by account size)',
    tradableInstruments: ['Futures (E-mini, Micro, etc.)'],
    platforms: ['NinjaTrader', 'Rithmic', 'Tradovate', 'TradingView (via Tradovate)'],
    rating: 4.7,
    isFeatured: true,
    minAccountSize: 25000,
    maxAccountSize: 300000,
    minChallengeCost: 137, // Example monthly cost for smallest account
    maxChallengeCost: 657, // Example monthly cost for largest account
    activationFee: 'None (for PA accounts)',
    challengeType: '1-Step Evaluation',
  },
  {
    id: '2',
    slug: 'fund-your-dreams',
    name: 'FundYourDreams',
    logoUrl: 'https://placehold.co/100x50.png?text=FYD',
    websiteUrl: '#',
    affiliateLink: '#',
    briefDescription: 'A newer firm with competitive pricing and a focus on trader growth. Excellent for beginners.',
    fullReview: 'Detailed review content for FundYourDreams...',
    pros: ['Affordable challenges', 'Supportive community', 'Regular promotions'],
    cons: ['Lower max funding compared to some', 'Newer reputation'],
    keyFeatures: ['Scaling plan', 'No time limits on challenges', 'Weekend holding allowed'],
     keyInfoSnippets: [
      { label: 'Profit Split', value: 'Up to 85%' },
      { label: 'Max Drawdown', value: '12% overall' },
      { label: 'Platforms', value: 'MT5' },
    ],
    offerBadgeLabel: 'Hot Offer',
    fundingModels: ['2-Step Challenge'],
    profitSplit: '80% - 85%',
    drawdownRules: '6% daily, 12% overall',
    profitTarget: '10% (Phase 1), 5% (Phase 2)',
    tradableInstruments: ['Forex', 'Metals', 'Indices'],
    platforms: ['MT5'],
    rating: 4.5,
    isFeatured: true,
    minAccountSize: 5000,
    maxAccountSize: 300000,
    minChallengeCost: 49,
    maxChallengeCost: 299,
    activationFee: '$99',
    challengeType: '2-Step',
  },
  {
    id: '3',
    slug: 'elite-trader-funding',
    name: 'EliteTraderFunding',
    logoUrl: 'https://placehold.co/100x50.png?text=Elite',
    websiteUrl: '#',
    affiliateLink: '#',
    briefDescription: 'Premium firm for experienced traders seeking large capital and advanced tools.',
    pros: ['Very high funding limits', 'Advanced trading platforms', 'Dedicated account manager'],
    cons: ['Higher challenge costs', 'More stringent requirements'],
    keyFeatures: ['Up to $5M funding', 'Customizable conditions', 'API access'],
    keyInfoSnippets: [
      { label: 'Profit Split', value: 'Up to 90%' },
      { label: 'Max Drawdown', value: '8% overall (static)' },
      { label: 'Platforms', value: 'Proprietary, MT5' },
    ],
    fundingModels: ['Instant Funding (Pro)', '3-Step Challenge'],
    profitSplit: '70% - 90%',
    drawdownRules: '4% daily, 8% static overall',
    profitTarget: 'Varies by model',
    tradableInstruments: ['All major classes', 'Options', 'Futures'],
    platforms: ['Proprietary Platform', 'MT5', 'Quantower'],
    rating: 4.9,
    isFeatured: false, 
    minAccountSize: 25000,
    maxAccountSize: 5000000,
    minChallengeCost: 250,
    maxChallengeCost: 2500,
    activationFee: 'Varies',
    challengeType: '3-Step, Instant',
  },
  {
    id: '4',
    slug: 'placeholder-featured-firm',
    name: 'Placeholder Featured Firm',
    logoUrl: 'https://placehold.co/100x50.png?text=PFF',
    websiteUrl: '#',
    affiliateLink: '#',
    briefDescription: 'Another great featured firm. Discover unique benefits and start your journey today.',
    fullReview: 'Full review coming soon for Placeholder Featured Firm.',
    pros: ['Benefit A', 'Benefit B'],
    cons: ['Consideration X', 'Consideration Y'],
    keyFeatures: ['Key Feature 1', 'Key Feature 2'],
    keyInfoSnippets: [
      { label: 'Profit Split', value: 'Up to 88%' },
      { label: 'Challenge Style', value: 'Flexible' },
    ],
    offerBadgeLabel: 'New Arrival',
    fundingModels: ['1-Step Challenge', 'Direct Funding'],
    profitSplit: '80% - 88%',
    drawdownRules: 'Flexible based on model',
    profitTarget: 'Varies',
    tradableInstruments: ['Forex', 'Crypto'],
    platforms: ['MT4', 'MT5', 'TradingView'],
    rating: 4.2,
    isFeatured: true, 
    minAccountSize: 25000,
    maxAccountSize: 500000,
    minChallengeCost: 149,
    maxChallengeCost: 499,
    activationFee: 'None',
    challengeType: '1-Step',
  },
];

export const mockArticles: Article[] = [
  {
    id: '1',
    slug: 'understanding-prop-firm-rules',
    title: 'Understanding Prop Firm Rules: A Beginner&apos;s Guide',
    publishedDate: '2024-05-20',
    category: 'Guides',
    featuredImageUrl: 'https://placehold.co/600x400.png',
    excerpt: 'Navigating the complex rules of prop firms can be daunting. This guide breaks it down for you.'
  },
  {
    id: '2',
    slug: 'top-5-mistakes-traders-make-in-challenges',
    title: 'Top 5 Mistakes Traders Make in Prop Firm Challenges',
    publishedDate: '2024-05-15',
    category: 'Trading Tips',
    featuredImageUrl: 'https://placehold.co/600x400.png',
    excerpt: 'Avoid these common pitfalls to increase your chances of getting funded.'
  },
  {
    id: '3',
    slug: 'crypto-prop-firms-the-new-frontier',
    title: 'Crypto Prop Firms: The New Frontier for Digital Asset Traders',
    publishedDate: '2024-05-28',
    category: 'Crypto',
    featuredImageUrl: 'https://placehold.co/600x400.png',
    excerpt: 'Explore how proprietary trading is expanding into the cryptocurrency market.'
  },
];

export const mockTradingResources: TradingResource[] = [
  {
    id: 'tr1',
    name: 'TradingView',
    slug: 'tradingview',
    logoUrl: 'https://placehold.co/100x50.png?text=TV',
    websiteUrl: '#',
    affiliateLink: '#',
    description: 'The best charting platform and social network for traders and investors.',
    resourceType: 'Tool',
  },
  {
    id: 'tr2',
    name: 'Babypips School of Pipsology',
    slug: 'babypips',
    logoUrl: 'https://placehold.co/100x50.png?text=BP',
    websiteUrl: '#',
    affiliateLink: '#',
    description: 'Free online course to learn Forex trading from beginner to advanced.',
    resourceType: 'Course',
  },
  {
    id: 'tr3',
    name: 'CoinDesk',
    slug: 'coindesk',
    logoUrl: 'https://placehold.co/100x50.png?text=CD',
    websiteUrl: '#',
    affiliateLink: '#',
    description: 'Leading news source for cryptocurrency, blockchain and digital assets.',
    resourceType: 'News',
  },
];

