
import type { GlobalOffer, PropFirm, Article, TradingResource } from './types';

export const mockGlobalOffers: GlobalOffer[] = [
  { id: '1', text: 'VISIBLE OFFER TEXT TEST', affiliateLink: '#', isActive: true },
  { id: '2', text: 'Take Profit Trader: Up to 90% profit split!', affiliateLink: '#', isActive: true },
  { id: '3', text: 'NewFirmX: 10% bonus on payout with code FINDER10', affiliateLink: '#', isActive: true },
];

export const mockPropFirms: PropFirm[] = [
  {
    id: '1',
    slug: 'apex-trader-funding',
    name: 'Apex Trader Funding',
    logoUrl: 'https://placehold.co/100x50.png?text=ApexTF',
    websiteUrl: 'https://apextraderfunding.com/',
    affiliateLink: '#', 
    briefDescription: 'Popular choice for futures traders, offering straightforward evaluation and scaling.',
    fullReview: 'Apex Trader Funding is well-regarded in the futures trading community for its simple evaluation process and generous profit splits. They primarily focus on futures contracts and offer a variety of account sizes to suit different trader needs. Their Rithmic-based connection is standard for futures platforms.',
    pros: ["Simple 1-step evaluation", "No daily drawdown limit on many accounts", "Trade on actual market data during evaluation", "Quick funding after passing"],
    cons: ["Primarily futures-focused", "Monthly fee for evaluation accounts until passed", "Trailing drawdown can be tricky for some"],
    keyFeatures: ['Pass in as few as 7 days', 'Up to 20 accounts allowed', 'Trade on NinjaTrader, Tradovate, Rithmic'],
    keyInfoSnippets: [
      { label: 'Profit Split', value: '90% (first $25k per account), then 80%' },
      { label: 'Max Drawdown', value: 'Trailing Threshold' },
      { label: 'Platforms', value: 'NinjaTrader, Rithmic, Tradovate' },
    ],
    offerBadgeLabel: 'Pass in 7 Days!',
    fundingModels: ['1-Step Evaluation'],
    profitSplit: '90% (first $25k), then 80%',
    drawdownRules: 'Trailing Threshold Drawdown (varies by account size)',
    profitTarget: '6% - 7% (varies by account size)',
    tradableInstruments: ['Futures (E-mini, Micro, etc.)'],
    platforms: ['NinjaTrader', 'Rithmic', 'Tradovate', 'TradingView (via Tradovate)'],
    rating: 4.7,
    isFeatured: true,
    minAccountSize: 25000,
    maxAccountSize: 300000,
    minChallengeCost: 137, 
    maxChallengeCost: 657, 
    activationFee: 'None (for PA accounts)',
    challengeType: '1-Step Evaluation',
  },
  {
    id: '2',
    slug: 'take-profit-trader',
    name: 'Take Profit Trader',
    logoUrl: 'https://placehold.co/100x50.png?text=TPT',
    websiteUrl: '#', // Replace with actual if known
    affiliateLink: '#', // Replace with actual affiliate link
    briefDescription: 'Futures trading prop firm with multiple evaluation options and fast payouts.',
    fullReview: 'Take Profit Trader offers various funding paths for futures traders, including different challenge types and account sizes. They emphasize quick payout processing and provide access to popular futures trading platforms. Their rules are generally straightforward, focusing on consistency and risk management.',
    pros: ['Multiple challenge types (1-step, 2-step)', 'Fast payout process', 'No scaling targets required for payout'],
    cons: ['Relatively newer in the space', 'Some rules can be strict depending on challenge type'],
    keyFeatures: ['Payouts in as little as 5 days', 'NinjaTrader and Tradovate support', 'End-of-Day drawdown option'],
     keyInfoSnippets: [
      { label: 'Profit Split', value: 'Up to 90%' },
      { label: 'Max Drawdown', value: 'Varies (EOD or Trailing)' },
      { label: 'Platforms', value: 'NinjaTrader, Tradovate' },
    ],
    offerBadgeLabel: 'Fast Payouts',
    fundingModels: ['1-Step Challenge', '2-Step Challenge'],
    profitSplit: '80% - 90%',
    drawdownRules: 'Varies by challenge: EOD or Trailing Drawdown',
    profitTarget: '6% - 10% (varies)',
    tradableInstruments: ['Futures'],
    platforms: ['NinjaTrader', 'Tradovate', 'TradingView (via Tradovate)'],
    rating: 4.6,
    isFeatured: true,
    minAccountSize: 25000,
    maxAccountSize: 150000,
    minChallengeCost: 150, // Example cost
    maxChallengeCost: 360, // Example cost
    activationFee: 'None (for PA accounts)', // Or specific fee if known
    challengeType: '1-Step, 2-Step',
  },
  {
    id: '3',
    slug: 'elite-trader-funding',
    name: 'EliteTraderFunding',
    logoUrl: 'https://placehold.co/100x50.png?text=Elite',
    websiteUrl: '#',
    affiliateLink: '#',
    briefDescription: 'Premium firm for experienced traders seeking large capital and advanced tools.',
    pros: ['Very high funding limits', 'Advanced trading platforms', 'Dedicated account manager'],
    cons: ['Higher challenge costs', 'More stringent requirements'],
    keyFeatures: ['Up to $5M funding', 'Customizable conditions', 'API access'],
    keyInfoSnippets: [
      { label: 'Profit Split', value: 'Up to 90%' },
      { label: 'Max Drawdown', value: '8% overall (static)' },
      { label: 'Platforms', value: 'Proprietary, MT5' },
    ],
    fundingModels: ['Instant Funding (Pro)', '3-Step Challenge'],
    profitSplit: '70% - 90%',
    drawdownRules: '4% daily, 8% static overall',
    profitTarget: 'Varies by model',
    tradableInstruments: ['All major classes', 'Options', 'Futures'],
    platforms: ['Proprietary Platform', 'MT5', 'Quantower'],
    rating: 4.9,
    isFeatured: false, 
    minAccountSize: 25000,
    maxAccountSize: 5000000,
    minChallengeCost: 250,
    maxChallengeCost: 2500,
    activationFee: 'Varies',
    challengeType: '3-Step, Instant',
  },
  {
    id: '4',
    slug: 'placeholder-featured-firm',
    name: 'Placeholder Featured Firm',
    logoUrl: 'https://placehold.co/100x50.png?text=PFF',
    websiteUrl: '#',
    affiliateLink: '#',
    briefDescription: 'Another great featured firm. Discover unique benefits and start your journey today.',
    fullReview: 'Full review coming soon for Placeholder Featured Firm.',
    pros: ['Benefit A', 'Benefit B'],
    cons: ['Consideration X', 'Consideration Y'],
    keyFeatures: ['Key Feature 1', 'Key Feature 2'],
    keyInfoSnippets: [
      { label: 'Profit Split', value: 'Up to 88%' },
      { label: 'Challenge Style', value: 'Flexible' },
    ],
    offerBadgeLabel: 'New Arrival',
    fundingModels: ['1-Step Challenge', 'Direct Funding'],
    profitSplit: '80% - 88%',
    drawdownRules: 'Flexible based on model',
    profitTarget: 'Varies',
    tradableInstruments: ['Forex', 'Crypto'],
    platforms: ['MT4', 'MT5', 'TradingView'],
    rating: 4.2,
    isFeatured: true, 
    minAccountSize: 25000,
    maxAccountSize: 500000,
    minChallengeCost: 149,
    maxChallengeCost: 499,
    activationFee: 'None',
    challengeType: '1-Step',
  },
];

export const mockArticles: Article[] = [
  {
    id: '1',
    slug: 'understanding-prop-firm-rules',
    title: 'Understanding Prop Firm Rules: A Beginner&apos;s Guide',
    publishedDate: '2024-05-20',
    category: 'Guides',
    featuredImageUrl: 'https://placehold.co/600x400.png',
    excerpt: 'Navigating the complex rules of prop firms can be daunting. This guide breaks it down for you.'
  },
  {
    id: '2',
    slug: 'top-5-mistakes-traders-make-in-challenges',
    title: 'Top 5 Mistakes Traders Make in Prop Firm Challenges',
    publishedDate: '2024-05-15',
    category: 'Trading Tips',
    featuredImageUrl: 'https://placehold.co/600x400.png',
    excerpt: 'Avoid these common pitfalls to increase your chances of getting funded.'
  },
  {
    id: '3',
    slug: 'crypto-prop-firms-the-new-frontier',
    title: 'Crypto Prop Firms: The New Frontier for Digital Asset Traders',
    publishedDate: '2024-05-28',
    category: 'Crypto',
    featuredImageUrl: 'https://placehold.co/600x400.png',
    excerpt: 'Explore how proprietary trading is expanding into the cryptocurrency market.'
  },
];

export const mockTradingResources: TradingResource[] = [
  {
    id: 'tr1',
    name: 'TradingView',
    slug: 'tradingview',
    logoUrl: 'https://placehold.co/100x50.png?text=TV',
    websiteUrl: '#',
    affiliateLink: '#',
    description: 'The best charting platform and social network for traders and investors.',
    resourceType: 'Tool',
  },
  {
    id: 'tr2',
    name: 'Babypips School of Pipsology',
    slug: 'babypips',
    logoUrl: 'https://placehold.co/100x50.png?text=BP',
    websiteUrl: '#',
    affiliateLink: '#',
    description: 'Free online course to learn Forex trading from beginner to advanced.',
    resourceType: 'Course',
  },
  {
    id: 'tr3',
    name: 'CoinDesk',
    slug: 'coindesk',
    logoUrl: 'https://placehold.co/100x50.png?text=CD',
    websiteUrl: '#',
    affiliateLink: '#',
    description: 'Leading news source for cryptocurrency, blockchain and digital assets.',
    resourceType: 'News',
  },
];

